[advisories]
ignore = [
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0 WITH LLVM-exception", # rm_rf -> ar_archive_writer
]

exceptions = [
    { allow = ["Unicode-3.0"], crate = "unicode-ident" },
]

[bans]
skip = [
    # "crate-name",
]

skip-tree = [
    # "crate-name",
]
